# wrangler.toml
name = "personal-website"
pages_build_output_dir = "./_site"
account_id = "3a95125f8c7c761e8e104541dccadbee"
# compatibility_date = "2025-08-16"  # optional; useful if you later add Pages Functions